### ISSUE TITLE
Is it possible to use zod objects within defineSchema function

### ISSUE THREAD

**Issue by noccer** [get-convex/convex-demos#19]
It's great to have the zod helpers in `zod-validation-ts` however is it possible to use my Zod types when constructing a defineSchema function?

**Comment by noccer** [comment]
And I should add- if using this function `send`:
https://github.com/get-convex/convex-demos/blob/main/zod-validation-ts/convex/messages.ts#L6

I would like to reuse the args in `defineTable` here:
https://github.com/get-convex/convex-demos/blob/main/zod-validation-ts/convex/schema.ts#L4

Hope that makes sense. At the moment it doesn't seem worth using zod if I still have to duplicate a schema in `defineTable`

Thanks ☘️

**Comment by thomasballinger** [comment]
It's not currently, and it'll be tricky to make this work.

We'd like argument validation to work in every language convex supports, so unless we can harvest language-agnostic type descriptions from Zod validators (which talking to Colin a few months ago does sound possible for a subset of Zod validators, just not all) we'll want to use our own validators.

However composing these somehow isn't out of the question, let's leave this open to think about this. Since Convex functions are written in JavaScript/TypeScript it makes sense to do validation with Zod.

BTW great question, also free to open this kind of issue at https://github.com/get-convex/convex-js since often that's the code in question.

**Comment by xixixao** [comment]
Thanks for the feedback!
